name: topbar_test
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.3
  hive_ce: any
  hive_ce_flutter: any

dev_dependencies:
  rexios_lints: ^10.1.0

dependency_overrides:
  hive_ce:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: cf372903350fe10e99480c9232f2a0805d96dd9c
      path: hive
  hive_ce_flutter:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: cf372903350fe10e99480c9232f2a0805d96dd9c
      path: hive_flutter
  hive_ce_generator:
    git:
      url: https://github.com/IO-Design-Team/hive_ce
      ref: cf372903350fe10e99480c9232f2a0805d96dd9c
      path: hive_generator

flutter:
  uses-material-design: true
